# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

# step 1: Install latest .NET Core SDK
# step 2: Set up .NET publish command
# step 3: Publish artifact
# step 4: script to push to github

variables:
- group: GitHubPATGroup

steps:
- task: UseDotNet@2
  displayName: Install latest .NET Core
  inputs:
    packageType: 'sdk'
    version: '3.1.200'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Set up .NET publish command
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: Publish artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- script: |
    git config --global user.name = "$NAME"
    git config --global user.email = "$EMAIL"
    cd $(Build.ArtifactStagingDirectory)/s/demoblazorci/dist/
    ls -la
    git init
    git checkout -b gh-pages-from-action
    git add -A
    git commit -m "Create build $(Build.BuildId)"
    git push -f https://$PAT@github.com/vienpt/blazordemoci gh-pages-from-action
  displayName: 'Publish to GitHub'
