name: CI Github pages

on:
  pull_request:
    branches: gh-pages-from-action

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#    - uses: actions/checkout@v1
#    - name: Set up .NET Core
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: '3.1.100'
    
#    - name: Publish app
#      run: dotnet publish -c Release -o build
    
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: gh-pages-from-action
        BRANCH: gh-pages
        FOLDER: build
        CLEAN: true
